name: Test React app

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node v14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
                   
      - name: Install dependencies
        working-directory: ./myapp  
        run: yarn
        
      - name: Run tests
        working-directory: ./myapp  
        run: yarn run test
        
      - name: Create production build
        working-directory: ./myapp  
        run: yarn run build
